export const INCREMENT_MODEL = 'INCREMENT_MODEL';
export const DECREMENT_MODEL = 'DECREMENT_MODEL';

export const INCREMENT_COLOR = 'INCREMENT_COLOR'
export const DECREMENT_COLOR = 'DECREMENT_COLOR';

export const INCREMENT_SPOILER = 'INCREMENT_SPOILER';
export const DECREMENT_SPOILER = 'DECREMENT_SPOILER';

export const INCREMENT_RIMS = 'INCREMENT_RIMS';
export const DECREMENT_RIMS = 'DECREMENT_RIMS';

export const INCREMENT_STICKERS = 'INCREMENT_STICKERS';
export const DECREMENT_STICKERS = 'DECREMENT_STICKERS';

export const INCREMENT_UNDERGLOW = 'INCREMENT_UNDERGLOW';
export const DECREMENT_UNDERGLOW = 'DECREMENT_UNDERGLOW';
